callback codemirror ext setup
rainlanguage/rain.orderbook pull request #192
Opened 2024-02-07 22:10 UTC by rouzwelt

2024-02-08 15:19 UTC, mattyg commented on crates/common/src/lsp_services.rs
> +                        position: [0, 0],
same note as above :)

2024-02-08 15:21 UTC, mattyg commented on tauri-app/src/lib/utils/langServices.ts
> +      position: [0, 0],
same note as above :)

2024-02-08 15:38 UTC, mattyg requested changes
just requesting changes to default error positions

2024-02-08 18:33 UTC, rouzwelt commented on crates/common/src/lsp_services.rs
> +                        position: [0, 0],
well errors that dont have definitive positions as an standard are usually set to the top of the doc, and personally I dont like the big red underline covering all of the text,

2024-02-08 18:58 UTC, thedavidmeister approved these changes

2024-02-08 21:39 UTC, mattyg commented on crates/common/src/lsp_services.rs
> +                        position: [0, 0],
I disagree -- it makes its unlikely that users will even notice they have linting errors.

This is how an error in linting the frontmatter appears to users in this PR
![image](https://github.com/rainlanguage/rain.orderbook/assets/159270/29ac4a0b-bbb0-46fa-bcc8-33c7c87a985b)

My preference would be to determine the *actual* position of the error. 

Without that it is preferable to make the error obvious by underlining the entire relevant section i.e. 
![image](https://github.com/rainlanguage/rain.orderbook/assets/159270/ac8f96d2-0082-4132-bdeb-91c775528389)

2024-02-08 21:46 UTC, mattyg requested changes
just realized the `parseDotrain` function is no longer used and can be deleted. I still feel like the unknown error locations could be clearer to the user. Otherwise looks good.

2024-02-09 17:27 UTC, mattyg commented on crates/common/src/lsp_services.rs
> +                        position: [0, 0],
We'll merge as-is for now and collect user feedback.

2024-02-09 17:27 UTC, mattyg approved these changes

2024-02-09 17:27 UTC, merged