2024 03 15 deposit allowance check
rainlanguage/rain.orderbook pull request #432
Opened 2024-03-16 07:20 UTC by mattyg

Resolves #403 

- Check allowance before calling approve
- Only request approval for allowance - amount

2024-03-18 08:51 UTC, thedavidmeister requested changes

2024-03-18 08:51 UTC, thedavidmeister commented on crates/common/src/deposit.rs
> +            ReadableClient::new_from_url(transaction_args.rpc_url.clone()).unwrap();
this will panic the app if you unwrap

2024-03-18 20:08 UTC, mattyg commented on crates/common/src/deposit.rs
> +            ReadableClient::new_from_url(transaction_args.rpc_url.clone()).unwrap();
whoops - good catch

2024-03-19 06:06 UTC, thedavidmeister approved these changes

2024-03-19 06:06 UTC, merged