setup doc
rainlanguage/rain.orderbook pull request #876
Opened 2024-09-19 22:13 UTC by rouzwelt

## Motivation
resolves #863 

## Solution

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [ ] unit-tested any new functionality
- [x] linked any relevant issues or PRs

2024-09-23 09:10 UTC, hardyjosh commented
<img width="476" alt="image" src="https://github.com/user-attachments/assets/ce15ebb1-3834-42d4-9dfa-eeb3a41e17ee">

2024-09-23 16:22 UTC, thedavidmeister requested changes

2024-09-23 16:22 UTC, thedavidmeister commented on SETUP.md
> +For deploying the contracts locally you need to have foundry (either installed locally or enter nix shell that puts everything on your path) and run the following command:
local deploys are not ok, not sure why this is here

2024-10-06 09:38 UTC, thedavidmeister requested changes
i don't think all caps .md docs in the root of this repo are where process level documentation should be

who is this for? the docs should be where that person is going to find them

2024-10-27 22:56 UTC, dcatki commented
@rouzwelt what's the status of this?

2024-11-01 22:54 UTC, rouzwelt commented
moved to org-process repo

2024-11-01 22:54 UTC, closed without merging