canary documentation
rainlanguage/rain.orderbook pull request #881
Opened 2024-09-23 19:11 UTC by rouzwelt

## Motivation
related to https://github.com/rainlanguage/arb-bot/issues/199

## Solution

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [ ] unit-tested any new functionality
- [x] linked any relevant issues or PRs

2024-10-05 17:37 UTC, thedavidmeister requested changes

2024-10-05 17:37 UTC, thedavidmeister commented on CANARY.md
> +# Canary strat
i don't really understand why this doc is here, in the root of the ob repo

or who it is for?

@rouzwelt originally i asked you to setup a canary, which is already documented in the strat in pubstrats in basically paraphrasing exactly what is here

```

# The canary order does nothing except run on a cooldown.
#
# It is useful only to show that orders clear on some network. If the canary is
# deployed and does not run, it means that there are no solvers monitoring the
# network, or at least not the raindex contract that the canary is deployed on.
#
# The canary is basically a stripped back version of the sampler. It runs but
# doesn't sample anything.
```

i'd expect to see docs that explain what was missing in your understanding when i asked you about it @rouzwelt and probably somewhere related to the infra they are for

2024-10-27 22:56 UTC, dcatki commented
@rouzwelt whats the status of this?

2024-12-04 22:04 UTC, rouzwelt commented
I guess this now can be closed in favor of the canary strats on web app? @thedavidmeister

2024-12-18 13:21 UTC, hardyjosh commented
closing this, not required anymore

2024-12-18 13:21 UTC, closed without merging