order dotrain meta
rainlanguage/rain.orderbook pull request #912
Opened 2024-10-01 03:59 UTC by rouzwelt

## Motivation
resolves #888 
resolves #889 

## Solution
emit filtered dotrain meta when adding order and decode it back from sg queries

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [x] unit-tested any new functionality
- [x] linked any relevant issues or PRs

2024-10-06 09:39 UTC, thedavidmeister requested changes

2024-10-06 09:39 UTC, thedavidmeister commented on crates/cli/src/commands/order/filter.rs
> +    pub include_gui: bool,
why wouldn't we include gui?

2024-10-27 22:57 UTC, dcatki commented
@rouzwelt this also

2024-12-02 14:29 UTC, thedavidmeister commented
the way this is is not useable for several reasons
- gui is way too big to include in full
- setting a bool as the author to include the gui or not doesn't make sense
- yaml implementation is being refactored in parallel

@rouzwelt @hardyjosh feel free to reopen if you disagree but i think we'll just have to revisit later

2024-12-02 14:29 UTC, closed without merging