Add network name to wallet connect error message
rainlanguage/rain.orderbook pull request #917
Opened 2024-10-04 14:03 UTC by findolor

## Motivation

## Solution

## Checks

By submitting this for review, I'm confirming I've done the following:
- [ ] made this PR as small as possible
- [ ] unit-tested any new functionality
- [ ] linked any relevant issues or PRs

2024-10-15 14:50 UTC, thedavidmeister requested changes
can we get a test for this?

and screenshot?

2024-10-16 05:18 UTC, findolor commented
@thedavidmeister I've included some tests and here are some screenshots:

![Screenshot 2024-10-16 at 07 24 02](https://github.com/user-attachments/assets/84dcdc80-6ad3-40f7-8127-f08715d9476f)
![Screenshot 2024-10-16 at 07 31 30](https://github.com/user-attachments/assets/8c79f53b-fa3a-4534-b481-906c19610f34)

2024-10-16 13:28 UTC, thedavidmeister requested changes

2024-10-16 13:28 UTC, thedavidmeister commented on tauri-app/src/lib/components/ModalExecute.test.ts
> +        'You are connected to unknown network. Please connect your wallet to test network.',
"an unknown" would be grammatically correct

2024-10-16 14:12 UTC, thedavidmeister approved these changes

2024-10-17 09:40 UTC, merged