net volume
rainlanguage/rain.orderbook pull request #922
Opened 2024-10-05 22:50 UTC by rouzwelt

## Motivation
resolves #905 

## Solution
<img width="895" alt="Screenshot 2024-10-05 at 10 47 49 PM" src="https://github.com/user-attachments/assets/9778ba79-8a3a-4053-95f6-756193733a7c">

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [x] unit-tested any new functionality
- [x] linked any relevant issues or PRs

2024-10-06 09:36 UTC, thedavidmeister requested changes

2024-10-06 09:36 UTC, thedavidmeister commented on tauri-app/src/lib/components/tables/OrderVaultsVolTable.svelte
> -      {formatUnits(BigInt(item.totalVol), Number(item.token.decimals ?? 0))}
i don't understand why we removed total volume? i was expecting to see both total and net

2024-10-08 18:24 UTC, thedavidmeister requested changes

2024-10-08 18:24 UTC, thedavidmeister commented on tauri-app/src/lib/components/tables/OrderVaultsVolTable.test.ts
> -        BigInt(mockVaultsVol[i].totalVol),
we lost the test for total vol?

2024-10-12 02:16 UTC, rouzwelt commented on tauri-app/src/lib/components/tables/OrderVaultsVolTable.test.ts
> -        BigInt(mockVaultsVol[i].totalVol),
fixed

2024-10-12 02:17 UTC, rouzwelt commented on tauri-app/src/lib/components/tables/OrderVaultsVolTable.test.ts
> -        BigInt(mockVaultsVol[i].totalVol),
@thedavidmeister added

2024-10-12 03:20 UTC, thedavidmeister approved these changes

2024-10-16 03:10 UTC, merged