Handle negative values and division operation
rainlanguage/rain.orderbook pull request #952
Opened 2024-10-21 07:09 UTC by findolor

## Motivation

See issue: #944

## Solution

- Multiply output value with -1
- Use `BigInt` values to correctly handle division

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [ ] unit-tested any new functionality
- [x] linked any relevant issues or PRs

2024-10-22 17:23 UTC, thedavidmeister requested changes
screenshots and tests

2024-10-23 04:49 UTC, findolor commented
All the trades render without negative values now:

<img width="1422" alt="Screenshot 2024-10-23 at 07 37 29" src="https://github.com/user-attachments/assets/9b0730f6-43c0-4230-8608-8c796f9e5586">

2024-10-23 14:15 UTC, thedavidmeister requested changes

2024-10-23 14:15 UTC, thedavidmeister commented on tauri-app/src/lib/components/tables/OrderTradesListTable.svelte
> +        (BigInt(10 ** 18) *
this should probably be abstracted in the same way that it is onchain

e.g. `a.mul(b)` is like `(a * b) / ONE` and `a.div(b)` is `(a * ONE) / b`

nobody writes solidity like this, for a reason :)

2024-10-24 12:52 UTC, closed without merging