bigint math toolings
rainlanguage/rain.orderbook pull request #971
Opened 2024-10-30 16:24 UTC by rouzwelt

## Motivation

## Solution

## Checks

By submitting this for review, I'm confirming I've done the following:
- [ ] made this PR as small as possible
- [ ] unit-tested any new functionality
- [ ] linked any relevant issues or PRs
- [ ] included screenshots (if this involves a front-end change)

2024-10-31 14:03 UTC, thedavidmeister requested changes

2024-10-31 14:03 UTC, thedavidmeister commented on crates/math/src/lib.rs
> +            .saturating_mul(U256::from(mul))
we should not be saturating here

2024-10-31 14:03 UTC, thedavidmeister commented on crates/math/src/lib.rs
> +            .checked_div(U256::from(div))
what does checked do on div? is it just divide by 0?

2024-10-31 14:03 UTC, thedavidmeister commented on crates/math/src/lib.rs
> +    Ok(parse_units(
why are we doing this with parsing? this runs through strings?

2024-11-13 16:59 UTC, thedavidmeister approved these changes

2024-11-13 17:06 UTC, hardyjosh approved these changes

2024-11-16 01:09 UTC, merged