Adding gui related fields to config
rainlanguage/rain.orderbook pull request #985
Opened 2024-11-08 12:13 UTC by findolor

## Motivation

See issue: https://github.com/rainlanguage/rain.orderbook/issues/964

This PR adds the gui field to config for future usage

## Solution

- Add new field `gui` to config source and config

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [x] unit-tested any new functionality
- [x] linked any relevant issues or PRs
- [ ] included screenshots (if this involves a front-end change)

2024-11-08 21:05 UTC, hardyjosh commented on crates/settings/src/gui.rs
> +    pub min: Option<f64>,
let's remove

2024-11-08 21:05 UTC, hardyjosh commented on crates/settings/src/gui.rs
> +    pub min: Option<f64>,
we were going to use json schema for validation

2024-11-08 21:06 UTC, hardyjosh commented on crates/settings/src/gui.rs
> +    min: Option<U256>,
remove in favour of json schema validation later

2024-11-08 21:07 UTC, hardyjosh commented on crates/settings/src/gui.rs
> +    pub min: Option<f64>,
remove

2024-11-11 14:52 UTC, hardyjosh requested changes

2024-11-11 14:52 UTC, hardyjosh commented on crates/settings/src/gui.rs
> +pub const GUI_PRESET_VALUE_DECIMALS: u8 = 18;
Do we need this anymore?

2024-11-11 14:58 UTC, findolor commented on crates/settings/src/gui.rs
> +pub const GUI_PRESET_VALUE_DECIMALS: u8 = 18;
No need for this, removing

2024-11-12 09:20 UTC, hardyjosh approved these changes

2024-11-12 09:20 UTC, merged