991 get vault balances for an order in cli
rainlanguage/rain.orderbook pull request #996
Opened 2024-11-13 11:50 UTC by ninokeldishvili

## Motivation
get vault balances for an order in cli

## Solution
Add the logic to get vault balances for orders in cli and telegram notifications

## Checks

By submitting this for review, I'm confirming I've done the following:
- [ ] made this PR as small as possible
- [ ] unit-tested any new functionality
- [ ] linked any relevant issues or PRs
- [ ] included screenshots (if this involves a front-end change)

2024-11-19 12:30 UTC, thedavidmeister requested changes

2024-11-19 12:30 UTC, thedavidmeister commented on crates/cli/src/balance.rs
> +        assert!(result.is_ok(), "Failed to fetch balances: {:?}", result);
we should be able to assert more than this, to check the structure of the return

2024-11-21 12:34 UTC, thedavidmeister requested changes

2024-11-21 12:34 UTC, thedavidmeister commented on crates/cli/src/balance.rs
> +                    first_order.get("owner").unwrap(),
this will break as soon as the subgraph returns different data

2024-11-21 12:34 UTC, thedavidmeister commented on crates/cli/src/balance.rs
> +            println!("Fetched balance data: {:?}", data);
what is this for?

2024-11-21 12:34 UTC, thedavidmeister commented on crates/cli/src/balance.rs
> +        //let subgraph_url = "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-mainnet/2024-10-25-af6a/gn";
commented code

2024-11-21 12:34 UTC, thedavidmeister commented on crates/cli/src/balance.rs
> +        //let orderbook_mainnet_subgraph_url = "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-mainnet/2024-10-25-af6a/gn";
commented code

2024-11-21 15:46 UTC, thedavidmeister requested changes

2024-11-21 15:46 UTC, thedavidmeister commented on crates/cli/src/balance.rs
> +    let hex_string = hex::encode(decoded_bytes); // Convert the decoded bytes back to a hex string
i don't understand why we decode and encode it again?

2024-11-22 15:40 UTC, thedavidmeister approved these changes

2025-01-20 05:51 UTC, hardyjosh requested changes
Can we use the already existing functions for getting a single order?

2025-02-21 16:35 UTC, hardyjosh commented
closing this for now as not required

2025-02-21 16:35 UTC, closed without merging